// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import oxlintCliManifestData from "./manifest.generated.json";

export { oxlintCliManifestData };
export const oxlintCliManifest = defineCliCommandManifest(oxlintCliManifestData);
