// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";

export const playwrightCliManifest = defineCliCommandManifest({
  schemaVersion: "toolchains-init/cli-command-manifest/v1",
  tool: "playwright",
  package: "create-playwright",
  version: "1.17.139",
  commands: [
    {
      id: "init",
      packageManagers: {
        npm: ["npm", "init", "playwright@{version}", "--"],
        pnpm: ["pnpm", "create", "playwright@{version}"],
        yarn: ["yarn", "create", "playwright@{version}"],
      },
      flags: {
        quiet: {
          type: "boolean",
          cliName: "--quiet",
          supported: true,
        },
        lang: {
          type: "enum",
          cliName: "--lang",
          values: ["js", "TypeScript"],
          supported: true,
        },
        noBrowsers: {
          type: "boolean",
          cliName: "--no-browsers",
          supported: true,
        },
      },
      interactive: true,
    },
  ],
  sources: [
    {
      kind: "npm",
      package: "create-playwright",
      version: "1.17.139",
      distTag: "latest",
      resolvedAt: "2025-10-08T07:38:09.036Z",
    },
    {
      kind: "cli-help",
      command: ["npx", "--yes", "create-playwright@1.17.139", "--help"],
    },
    {
      kind: "docs",
      url: "https://playwright.dev/docs/intro",
      confidence: "medium",
    },
  ],
});
