// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import playwrightCliManifestData from "./manifest.generated.json";

export { playwrightCliManifestData };
export const playwrightCliManifest = defineCliCommandManifest(playwrightCliManifestData);
