name: Setup
description: Install Node and Yarn dependencies.

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: yarn install
