// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import publintCliManifestData from "./manifest.generated.json";

export { publintCliManifestData };
export const publintCliManifest = defineCliCommandManifest(publintCliManifestData);
