// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import oxfmtCliManifestData from "./manifest.generated.json";

export { oxfmtCliManifestData };
export const oxfmtCliManifest = defineCliCommandManifest(oxfmtCliManifestData);
