// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";

export const oxfmtCliManifest = defineCliCommandManifest({
  schemaVersion: "toolchains-init/cli-command-manifest/v1",
  tool: "oxfmt",
  package: "oxfmt",
  version: "0.57.0",
  commands: [
    {
      id: "init",
      packageManagers: {
        npm: ["npx", "oxfmt@{version}"],
        pnpm: ["pnpm", "dlx", "oxfmt@{version}"],
        yarn: ["yarn", "dlx", "oxfmt@{version}"],
      },
      flags: {
        init: {
          type: "boolean",
          cliName: "--init",
          supported: true,
        },
      },
      interactive: false,
    },
  ],
  sources: [
    {
      kind: "npm",
      package: "oxfmt",
      version: "0.57.0",
      distTag: "latest",
      resolvedAt: "2026-06-29T23:08:50.068Z",
    },
    {
      kind: "cli-help",
      command: ["npx", "--yes", "oxfmt@0.57.0", "--help"],
    },
  ],
});
