// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import changesetsCliManifestData from "./manifest.generated.json";

export { changesetsCliManifestData };
export const changesetsCliManifest = defineCliCommandManifest(changesetsCliManifestData);
