// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import attwCliManifestData from "./manifest.generated.json";

export { attwCliManifestData };
export const attwCliManifest = defineCliCommandManifest(attwCliManifestData);
