// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";

export const knipCliManifest = defineCliCommandManifest({
  schemaVersion: "toolchains-init/cli-command-manifest/v1",
  tool: "knip",
  package: "knip",
  version: "6.24.0",
  commands: [
    {
      id: "check",
      packageManagers: {
        npm: ["npx", "knip@{version}"],
        pnpm: ["pnpm", "dlx", "knip@{version}"],
        yarn: ["yarn", "dlx", "knip@{version}"],
      },
      interactive: false,
    },
  ],
  sources: [
    {
      kind: "npm",
      package: "knip",
      version: "6.24.0",
      distTag: "latest",
      resolvedAt: "2026-07-02T06:36:36.617Z",
    },
    {
      kind: "cli-help",
      command: ["npx", "--yes", "knip@6.24.0", "--help"],
    },
  ],
});
