// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import knipCliManifestData from "./manifest.generated.json";

export { knipCliManifestData };
export const knipCliManifest = defineCliCommandManifest(knipCliManifestData);
