// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import shadcnCliManifestData from "./manifest.generated.json";

export { shadcnCliManifestData };
export const shadcnCliManifest = defineCliCommandManifest(shadcnCliManifestData);
