// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import yarnSdksCliManifestData from "./manifest.generated.json";

export { yarnSdksCliManifestData };
export const yarnSdksCliManifest = defineCliCommandManifest(yarnSdksCliManifestData);
