// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import storybookCliManifestData from "./manifest.generated.json";

export { storybookCliManifestData };
export const storybookCliManifest = defineCliCommandManifest(storybookCliManifestData);
