// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import cspellCliManifestData from "./manifest.generated.json";

export { cspellCliManifestData };
export const cspellCliManifest = defineCliCommandManifest(cspellCliManifestData);
