// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import prismaCliManifestData from "./manifest.generated.json";

export { prismaCliManifestData };
export const prismaCliManifest = defineCliCommandManifest(prismaCliManifestData);
