// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import tanStackRouterCliManifestData from "./manifest.generated.json";

export { tanStackRouterCliManifestData };
export const tanStackRouterCliManifest = defineCliCommandManifest(tanStackRouterCliManifestData);
