// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import supabaseCliManifestData from "./manifest.generated.json";

export { supabaseCliManifestData };
export const supabaseCliManifest = defineCliCommandManifest(supabaseCliManifestData);
