import { execFile } from "node:child_process";
import { access, mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";
import type { CliCommandManifest } from "../src/core/cli-command-manifest";
import { defineCliCommandManifest } from "../src/core/cli-command-manifest";
import type { PackageManager } from "../src/core/package-manager";
import type {
  PackageManagerCommandTemplates,
  ToolchainAdapter,
} from "../src/core/toolchain-adapter";
import { getToolchainCliTool, getToolchainId } from "../src/core/toolchain-adapter";

type CliHelpSource = Extract<CliCommandManifest["sources"][number], { kind: "cli-help" }>;
type NpmSource = Extract<CliCommandManifest["sources"][number], { kind: "npm" }>;

const execFileAsync = promisify(execFile);
const shouldCheck = process.argv.includes("--check");
const generatedFileHeader =
  "// Generated by scripts/update-cli-manifests.ts. Do not edit directly.";
const npmProbeTimeoutMs = 30_000;
const docsProbeTimeoutMs = 30_000;
const helpProbeTimeoutMs = 120_000;
const formatTimeoutMs = 60_000;
const packageManagerNames = ["npm", "pnpm", "yarn", "bun", "deno"] as const;
const genericValueHints = new Set([
  "boolean",
  "dir",
  "directory",
  "file",
  "name",
  "null",
  "number",
  "package",
  "path",
  "string",
  "value",
]);

if (isMainModule()) {
  try {
    await main();
  } catch (error) {
    console.error(formatError(error));
    process.exitCode = 1;
  }
}

export async function main() {
  const toolchains = await discoverToolchains();
  await validateDiscoveredToolchains(toolchains);
  const manifestInputs = toolchains.flatMap((toolchain) =>
    toolchain.adapter.cli == null ? [] : [createManifestInput(toolchain.adapter)],
  );

  const generatedFiles: GeneratedFile[] = [renderToolchainsRegistry(toolchains)];

  for (const input of manifestInputs) {
    const manifest = await createManifestWithLog(input);
    generatedFiles.push(...renderManifestFiles(input, manifest));
  }
  generatedFiles.push(renderManifestRegistry(manifestInputs));

  const formattedFiles = await formatInTempDir(generatedFiles);
  const fileStatuses = await getGeneratedFileStatuses(formattedFiles);
  const orphanedFiles = await findOrphanGeneratedFiles(formattedFiles.map((file) => file.path));

  if (shouldCheck) {
    logGeneratedFileSummary("check", fileStatuses, orphanedFiles);
    await checkGeneratedFiles(fileStatuses, orphanedFiles);
  } else {
    await writeGeneratedFiles(formattedFiles);
    await removeOrphanGeneratedFiles(orphanedFiles);
    logGeneratedFileSummary("update", fileStatuses, orphanedFiles);
  }
}

type GeneratedFile = {
  path: string;
  content: string;
};

type GeneratedFileStatus = GeneratedFile & {
  status: "added" | "changed" | "unchanged";
};

export type DiscoveredToolchain = {
  adapter: ToolchainAdapter;
  exportName: string;
  stackDir: string;
};

type ManifestInput = {
  commandId: string;
  docs: NonNullable<NonNullable<ToolchainAdapter["cli"]>["docs"]>;
  distTag: string;
  exportName: string;
  help: false | undefined;
  interactive: boolean;
  packageManagers: readonly PackageManager[];
  packageName: string;
  runner: NonNullable<NonNullable<ToolchainAdapter["cli"]>["runner"]>;
  stackDir: string;
  subcommand: string | null;
  tool: string;
};

function createManifestInput(toolchain: ToolchainAdapter): ManifestInput {
  const cli = toolchain.cli;
  if (cli == null) {
    throw new Error(`Missing CLI definition for ${toolchain.feature}`);
  }

  const tool = cli.tool ?? kebabCase(toolchain.feature);
  return {
    commandId: cli.commandId ?? cli.command,
    distTag: cli.distTag ?? "latest",
    docs: cli.docs ?? [],
    exportName: cli.exportName ?? `${toolchain.feature}CliManifest`,
    help: cli.help,
    interactive: toolchain.nonInteractive?.supported === false,
    packageManagers: cli.packageManagers ?? ["npm", "pnpm", "yarn", "bun", "deno"],
    packageName: cli.package,
    runner: cli.runner ?? "auto",
    stackDir: cli.stackDir ?? tool,
    subcommand: cli.subcommand === undefined ? cli.command : cli.subcommand,
    tool,
  };
}

export async function validateDiscoveredToolchains(toolchains: readonly DiscoveredToolchain[]) {
  assertUniqueIdentity(toolchains, "feature", (toolchain) => toolchain.adapter.feature);
  assertUniqueIdentity(toolchains, "toolchain selector", (toolchain) =>
    getToolchainId(toolchain.adapter),
  );
  assertUniqueIdentity(toolchains, "adapter export name", (toolchain) => toolchain.exportName);
  for (const toolchain of toolchains) {
    assertCanonicalFeature(toolchain.adapter.feature);
    assertDirectSelector(toolchain.adapter);
    if (toolchain.adapter.managedCli != null && toolchain.adapter.cli == null) {
      throw new Error(
        `Managed CLI adapter ${toolchain.adapter.feature} must declare a CLI command`,
      );
    }
  }

  const cliToolchains = toolchains.filter(
    (
      toolchain,
    ): toolchain is DiscoveredToolchain & {
      adapter: ToolchainAdapter & { cli: NonNullable<ToolchainAdapter["cli"]> };
    } => toolchain.adapter.cli != null,
  );
  const manifestInputs = cliToolchains.map((toolchain) => createManifestInput(toolchain.adapter));
  for (const input of manifestInputs) {
    assertSafeStackDir(input);
    assertPackageManagerContract(input);
  }
  assertUniqueIdentity(manifestInputs, "CLI tool", (input) => input.tool);
  assertUniqueIdentity(manifestInputs, "manifest export name", (input) => input.exportName);
  assertUniqueIdentity(manifestInputs, "stack path", (input) => getStackDir(input));
  assertUniqueIdentity(toolchains, "direct CLI selector", (toolchain) =>
    toolchain.adapter.cli == null
      ? getToolchainId(toolchain.adapter)
      : getToolchainCliTool(toolchain.adapter),
  );

  await Promise.all(
    cliToolchains.map(async (toolchain) => {
      const { docs } = toolchain.adapter.cli;
      if (docs == null || docs.length === 0) {
        throw new Error(
          `CLI adapter ${toolchain.adapter.feature} must declare docs review metadata`,
        );
      }

      await Promise.all(
        docs.map(async (doc, index) => {
          const context = `CLI adapter ${toolchain.adapter.feature} docs[${index}]`;
          const review = doc.review;
          if (review == null || review.reason.trim().length === 0) {
            throw new Error(`${context} must declare a nonempty review reason`);
          }

          assertNonEmptyStrings(review.mustContain, `${context} review.mustContain`);
          assertNonEmptyStrings(review.checks, `${context} review.checks`);
          assertNonEmptyStrings(review.files, `${context} review.files`);

          await Promise.all(
            review.files.map(async (file) => {
              const resolvedFile = resolveReviewFile(file, context);
              let fileStats;
              try {
                fileStats = await stat(resolvedFile);
              } catch {
                throw new Error(`${context} references a missing review file: ${file}`);
              }
              if (!fileStats.isFile()) {
                throw new Error(`${context} review path is not a file: ${file}`);
              }
            }),
          );
        }),
      );
    }),
  );
}

function assertSafeStackDir(input: ManifestInput) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(input.stackDir)) {
    throw new Error(
      `CLI adapter ${input.tool} stack path must be one lowercase kebab-case directory: ${input.stackDir}`,
    );
  }

  const stacksRoot = path.resolve("src", "stacks");
  const relative = path.relative(stacksRoot, getStackDir(input));
  if (relative.length === 0 || relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`CLI adapter ${input.tool} stack path must stay under src/stacks`);
  }
}

function assertPackageManagerContract(input: ManifestInput) {
  if (input.packageManagers.length === 0) {
    throw new Error(`CLI adapter ${input.tool} must support at least one package manager`);
  }

  const duplicate = input.packageManagers.find(
    (packageManager, index) => input.packageManagers.indexOf(packageManager) !== index,
  );
  if (duplicate != null) {
    throw new Error(`CLI adapter ${input.tool} repeats package manager: ${duplicate}`);
  }

  const { runner } = input;
  if (typeof runner === "object") {
    const templatePackageManagers = packageManagerNames.filter(
      (packageManager) => runner[packageManager] != null,
    );
    const invalidTemplate = templatePackageManagers.find((packageManager) => {
      const template = runner[packageManager];
      return template == null || template.length === 0 || template[0]?.trim().length === 0;
    });
    if (invalidTemplate != null) {
      throw new Error(
        `CLI adapter ${input.tool} runner template needs a nonempty binary: ${invalidTemplate}`,
      );
    }
    const missingTemplate = input.packageManagers.find(
      (packageManager) => !templatePackageManagers.includes(packageManager),
    );
    if (missingTemplate != null) {
      throw new Error(
        `CLI adapter ${input.tool} has no runner template for declared package manager: ${missingTemplate}`,
      );
    }
    const undeclaredTemplate = templatePackageManagers.find(
      (packageManager) => !input.packageManagers.includes(packageManager),
    );
    if (undeclaredTemplate != null) {
      throw new Error(
        `CLI adapter ${input.tool} has an undeclared runner template: ${undeclaredTemplate}`,
      );
    }
  }
}

function assertCanonicalFeature(feature: string) {
  if (!/^[a-z][A-Za-z0-9]*$/.test(feature)) {
    throw new Error(`Toolchain feature must use lowerCamelCase: ${feature}`);
  }
}

function assertDirectSelector(adapter: ToolchainAdapter) {
  const selector = adapter.cli == null ? getToolchainId(adapter) : getToolchainCliTool(adapter);
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(selector)) {
    throw new Error(`Direct CLI selector must use lowercase kebab-case: ${selector}`);
  }
  if (
    new Set(["help", "no-install", "package-manager", "target", "version", "yes"]).has(selector)
  ) {
    throw new Error(`Direct CLI selector is reserved: ${selector}`);
  }
}

function resolveReviewFile(file: string, context: string) {
  if (path.isAbsolute(file)) {
    throw new Error(`${context} review file must be repo-relative: ${file}`);
  }

  const repoRoot = process.cwd();
  const resolved = path.resolve(repoRoot, file);
  const relative = path.relative(repoRoot, resolved);
  if (relative.length === 0 || relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`${context} review file must stay inside the repository: ${file}`);
  }
  return resolved;
}

function assertUniqueIdentity<T>(
  values: readonly T[],
  label: string,
  getIdentity: (value: T) => string,
) {
  const owners = new Map<string, number>();
  for (const value of values) {
    const identity = getIdentity(value);
    const count = (owners.get(identity) ?? 0) + 1;
    owners.set(identity, count);
    if (count > 1) {
      throw new Error(`Duplicate ${label}: ${identity}`);
    }
  }
}

function assertNonEmptyStrings(values: readonly string[] | undefined, label: string) {
  if (values == null || values.length === 0 || values.some((value) => value.trim().length === 0)) {
    throw new Error(`${label} must contain at least one nonempty value`);
  }
}

async function discoverToolchains(): Promise<DiscoveredToolchain[]> {
  const stacksDir = path.resolve("src", "stacks");
  const stackDirs = await readdir(stacksDir, { withFileTypes: true });
  const discovered = (
    await Promise.all(
      stackDirs.flatMap(async (entry) => {
        if (!entry.isDirectory()) {
          return [];
        }

        const adapterPath = path.join(stacksDir, entry.name, "adapter.ts");
        try {
          await access(adapterPath);
        } catch {
          return [];
        }

        const module = (await import(pathToFileURL(adapterPath).href)) as Record<string, unknown>;
        return Object.entries(module).flatMap(([exportName, exported]) =>
          isToolchainAdapter(exported)
            ? [{ adapter: exported, exportName, stackDir: entry.name }]
            : [],
        );
      }),
    )
  ).flat();

  return discovered.sort(compareDiscoveredToolchains);
}

function isToolchainAdapter(value: unknown): value is ToolchainAdapter {
  return (
    value != null &&
    typeof value === "object" &&
    "feature" in value &&
    typeof value.feature === "string" &&
    "label" in value &&
    typeof value.label === "string" &&
    "hint" in value &&
    typeof value.hint === "string"
  );
}

function compareDiscoveredToolchains(left: DiscoveredToolchain, right: DiscoveredToolchain) {
  return (
    (left.adapter.order ?? 1000) - (right.adapter.order ?? 1000) ||
    left.stackDir.localeCompare(right.stackDir) ||
    left.exportName.localeCompare(right.exportName)
  );
}

async function createManifest(input: ManifestInput): Promise<CliCommandManifest> {
  const { publishedAt, version } = shouldCheck
    ? await readPinnedPackageVersion(input)
    : await resolvePackageVersion(input.packageName, input.distTag);
  const docsSources = await createDocsSources(input.docs);
  const manifest = defineCliCommandManifest({
    schemaVersion: "toolchains-init/cli-command-manifest/v1",
    tool: input.tool,
    package: input.packageName,
    version,
    commands: [
      {
        id: input.commandId,
        packageManagers: resolvePackageManagerCommands(input, version),
        interactive: input.interactive,
      },
    ],
    sources: [
      {
        kind: "npm",
        package: input.packageName,
        version,
        distTag: input.distTag,
        resolvedAt: publishedAt,
      },
      ...(input.help === false
        ? []
        : [
            {
              kind: "cli-help" as const,
              command: createHelpCommand(input, version),
              commandId: input.commandId,
            },
          ]),
      ...docsSources,
    ],
  });

  return defineCliCommandManifest({
    ...manifest,
    commands: await Promise.all(
      manifest.commands.map(async (command) => ({
        ...command,
        flags: await deriveFlagsForCommand(manifest, command.id),
      })),
    ),
  });
}

async function createManifestWithLog(input: ManifestInput) {
  console.log(
    `manifest ${input.tool}: ${shouldCheck ? "checking pinned" : "resolving"} ${input.packageName}@${input.distTag}`,
  );

  try {
    const manifest = await createManifest(input);
    const commandSummary = manifest.commands
      .map((command) => {
        const flagCount = Object.keys(command.flags ?? {}).length;
        return `${command.id} (${flagCount} flags)`;
      })
      .join(", ");
    console.log(
      `manifest ${input.tool}: ${manifest.package}@${manifest.version}; ${commandSummary}`,
    );
    return manifest;
  } catch (error) {
    throw new Error(`Failed to generate CLI manifest for ${input.tool}: ${formatError(error)}`);
  }
}

async function createDocsSources(docs: ManifestInput["docs"]) {
  return Promise.all(
    docs.map(async (doc) => {
      const checks = await checkDocsContent(doc);
      return {
        kind: "docs" as const,
        ...doc,
        ...(checks.length > 0 ? { checks } : {}),
      };
    }),
  );
}

async function checkDocsContent(doc: ManifestInput["docs"][number]) {
  const expectedTexts = doc.review?.mustContain ?? [];
  if (expectedTexts.length === 0) {
    return [];
  }

  const response = await fetch(doc.url, {
    headers: {
      "user-agent": "toolchains-init-manifest-bot",
    },
    signal: AbortSignal.timeout(docsProbeTimeoutMs),
  });
  if (!response.ok) {
    throw new Error(`Could not fetch docs for manifest source: ${doc.url} (${response.status})`);
  }

  const content = normalizeDocsContent(await response.text());
  const checks = expectedTexts.map((text) => ({
    found: content.includes(normalizeDocsContent(text)),
    text,
  }));
  const missing = checks.filter((check) => !check.found);
  if (missing.length > 0) {
    throw new Error(
      `Docs source no longer contains expected text: ${doc.url}\n${missing
        .map((check) => `- ${check.text}`)
        .join("\n")}`,
    );
  }

  return checks;
}

function normalizeDocsContent(content: string) {
  return content
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, " ")
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, " ")
    .replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi, " ")
    .replace(/<!--[\s\S]*?-->/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

async function resolvePackageVersion(packageName: string, distTag: string) {
  const { stdout } = await execFileAsync(
    "npm",
    ["view", packageName, `dist-tags.${distTag}`, "--json"],
    {
      encoding: "utf8",
      maxBuffer: 1024 * 1024,
      timeout: npmProbeTimeoutMs,
    },
  );
  const parsed = JSON.parse(stdout) as unknown;
  if (typeof parsed !== "string" || parsed.length === 0) {
    throw new Error(`Could not resolve ${packageName}@${distTag}`);
  }

  const { stdout: timeStdout } = await execFileAsync(
    "npm",
    ["view", `${packageName}@${parsed}`, "time", "--json"],
    {
      encoding: "utf8",
      maxBuffer: 1024 * 1024,
      timeout: npmProbeTimeoutMs,
    },
  );
  const time = JSON.parse(timeStdout) as Record<string, unknown>;
  const publishedAt = time[parsed];
  if (typeof publishedAt !== "string" || publishedAt.length === 0) {
    throw new Error(`Could not resolve publish time for ${packageName}@${parsed}`);
  }

  return { publishedAt, version: parsed };
}

async function readPinnedPackageVersion(input: ManifestInput) {
  const manifest = defineCliCommandManifest(
    JSON.parse(await readFile(getGeneratedManifestPath(input), "utf8")),
  );
  const npmSource = manifest.sources.find(
    (source): source is NpmSource => source.kind === "npm" && source.package === input.packageName,
  );
  if (npmSource == null) {
    throw new Error(
      `Generated CLI manifest for ${input.tool} has no npm source. Run yarn manifests:update.`,
    );
  }
  if (manifest.package !== input.packageName) {
    throw new Error(
      `Generated CLI manifest for ${input.tool} uses ${manifest.package}, expected ${input.packageName}. Run yarn manifests:update.`,
    );
  }

  return { publishedAt: npmSource.resolvedAt, version: manifest.version };
}

export async function runHelpCommand(command: readonly string[], timeoutMs = helpProbeTimeoutMs) {
  const [bin, ...args] = command;
  if (bin == null) {
    throw new Error("Help command has no binary");
  }

  try {
    const { stdout, stderr } = await execFileAsync(bin, args, {
      encoding: "utf8",
      maxBuffer: 10 * 1024 * 1024,
      timeout: timeoutMs,
    });
    return `${stdout}\n${stderr}`;
  } catch (error) {
    const output = getProcessOutput(error);
    if (!isTimedOutProcess(error) && hasPlausibleHelpSyntax(output)) {
      return output;
    }
    throw error;
  }
}

export function hasPlausibleHelpSyntax(output: string) {
  return (
    /(?:^|\n)\s*(?:usage|options)\s*:/im.test(output) ||
    /(?:^|\n)\s*(?:-[A-Za-z0-9],?\s+)?--[A-Za-z0-9][A-Za-z0-9-]*/m.test(output)
  );
}

function isTimedOutProcess(error: unknown) {
  return error != null && typeof error === "object" && "killed" in error && error.killed === true;
}

function getProcessOutput(error: unknown) {
  if (error == null || typeof error !== "object") {
    return "";
  }

  return `${stringifyProcessOutput("stdout" in error ? error.stdout : undefined)}\n${stringifyProcessOutput(
    "stderr" in error ? error.stderr : undefined,
  )}`;
}

function stringifyProcessOutput(output: unknown) {
  if (typeof output === "string") {
    return output;
  }
  if (output instanceof Uint8Array) {
    return Buffer.from(output).toString("utf8");
  }
  return "";
}

function renderManifestFiles(input: ManifestInput, manifest: CliCommandManifest) {
  return [
    {
      path: getGeneratedManifestPath(input),
      content: `${JSON.stringify(manifest, null, 2)}\n`,
    },
    {
      path: path.join(getStackDir(input), "manifest.ts"),
      content: renderManifestWrapper(input.exportName),
    },
  ];
}

function getGeneratedManifestPath(input: ManifestInput) {
  return path.join(getStackDir(input), "manifest.generated.json");
}

function getStackDir(input: ManifestInput) {
  return path.resolve("src", "stacks", input.stackDir);
}

async function checkGeneratedFiles(
  files: readonly GeneratedFileStatus[],
  orphanedFiles: readonly string[],
) {
  const staleFiles = files.filter((file) => file.status !== "unchanged").map((file) => file.path);
  if (staleFiles.length > 0 || orphanedFiles.length > 0) {
    throw new Error(
      `Stale CLI manifests. Run yarn manifests:update.\n${[...staleFiles, ...orphanedFiles]
        .map((file) => `- ${path.relative(process.cwd(), file)}`)
        .join("\n")}`,
    );
  }
}

async function getGeneratedFileStatuses(
  files: readonly GeneratedFile[],
): Promise<GeneratedFileStatus[]> {
  return Promise.all(
    files.map(async (file) => {
      try {
        const current = await readFile(file.path, "utf8");
        return {
          ...file,
          status: current === file.content ? ("unchanged" as const) : ("changed" as const),
        };
      } catch {
        return { ...file, status: "added" as const };
      }
    }),
  );
}

async function writeGeneratedFiles(files: readonly GeneratedFile[]) {
  for (const file of files) {
    await mkdir(path.dirname(file.path), { recursive: true });
    await writeFile(file.path, file.content);
  }
}

export async function findOrphanGeneratedFiles(
  expectedFiles: readonly string[],
  stacksDir = path.resolve("src", "stacks"),
) {
  const expected = new Set(expectedFiles.map((file) => path.resolve(file)));
  const entries = await readdir(stacksDir, { withFileTypes: true });
  const candidates = (
    await Promise.all(
      entries.flatMap(async (entry) => {
        if (!entry.isDirectory()) {
          return [];
        }

        const stackDir = path.join(stacksDir, entry.name);
        const generatedManifest = path.join(stackDir, "manifest.generated.json");
        const wrapper = path.join(stackDir, "manifest.ts");
        const files: string[] = [];
        try {
          await access(generatedManifest);
          files.push(generatedManifest);
        } catch {
          // No generated manifest in this stack.
        }
        try {
          const content = await readFile(wrapper, "utf8");
          if (content.startsWith(generatedFileHeader)) {
            files.push(wrapper);
          }
        } catch {
          // No generated wrapper in this stack.
        }
        return files;
      }),
    )
  ).flat();

  return candidates.filter((file) => !expected.has(path.resolve(file))).sort();
}

export async function removeOrphanGeneratedFiles(files: readonly string[]) {
  await Promise.all(files.map((file) => rm(file, { force: true })));
}

function logGeneratedFileSummary(
  mode: "check" | "update",
  files: readonly GeneratedFileStatus[],
  orphanedFiles: readonly string[],
) {
  const changedFiles = files.filter((file) => file.status !== "unchanged");
  const heading = mode === "check" ? "CLI manifest check result" : "CLI manifest update result";
  console.log("");
  console.log(heading);
  console.log(`- generated files: ${files.length}`);
  console.log(`- changed files: ${changedFiles.length}`);
  console.log(`- orphaned files: ${orphanedFiles.length}`);

  if (changedFiles.length === 0 && orphanedFiles.length === 0) {
    console.log("- status: up to date");
    return;
  }

  for (const file of changedFiles) {
    console.log(`- ${file.status}: ${path.relative(process.cwd(), file.path)}`);
  }
  for (const file of orphanedFiles) {
    console.log(
      `- ${mode === "check" ? "orphaned" : "removed"}: ${path.relative(process.cwd(), file)}`,
    );
  }
}

async function formatGeneratedFiles(filePaths: readonly string[]) {
  await execFileAsync("yarn", ["oxfmt", "--write", ...filePaths], {
    encoding: "utf8",
    maxBuffer: 10 * 1024 * 1024,
    timeout: formatTimeoutMs,
  });
}

async function formatInTempDir(files: readonly GeneratedFile[]) {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "toolchains-init-manifests-"));
  try {
    const tempFiles = await Promise.all(
      files.map(async (file) => {
        const relativePath = path.relative(process.cwd(), file.path);
        const tempPath = path.join(tempDir, relativePath);
        await mkdir(path.dirname(tempPath), { recursive: true });
        await writeFile(tempPath, file.content);
        return { ...file, path: tempPath, originalPath: file.path };
      }),
    );
    await formatGeneratedFiles(tempFiles.map((file) => file.path));
    return Promise.all(
      tempFiles.map(async (file) => ({
        ...file,
        content: await readFile(file.path, "utf8"),
        path: file.originalPath,
      })),
    );
  } finally {
    await rm(tempDir, { force: true, recursive: true });
  }
}

async function deriveFlagsForCommand(manifest: CliCommandManifest, commandId: string) {
  const helpSources = manifest.sources.filter((source): source is CliHelpSource =>
    isCliHelpForCommand(source, commandId, manifest.commands.length),
  );
  const flags: Record<string, ParsedHelpFlag> = {};
  for (const flag of (
    await Promise.all(
      helpSources.map(async (source) => parseHelpFlags(await runHelpCommand(source.command))),
    )
  ).flat()) {
    flags[toFlagKey(flag.cliName)] ??= flag;
  }

  return Object.keys(flags).length > 0 ? flags : undefined;
}

export type ParsedHelpFlag =
  | {
      type: "boolean";
      cliName: string;
      supported: true;
    }
  | {
      type: "string";
      cliName: string;
      supported: true;
    }
  | {
      type: "enum";
      cliName: string;
      values: string[];
      supported: true;
    };

export function parseHelpFlags(helpOutput: string): ParsedHelpFlag[] {
  const flags: ParsedHelpFlag[] = [];
  const seen = new Set<string>();

  for (const line of collectHelpFlagLines(helpOutput)) {
    for (const flag of parseHelpFlagLine(line)) {
      if (seen.has(flag.cliName)) {
        continue;
      }
      seen.add(flag.cliName);
      flags.push(flag);
    }
  }

  return flags;
}

function collectHelpFlagLines(helpOutput: string) {
  const lines: string[] = [];
  let current: string | undefined;

  const flush = () => {
    if (current != null) {
      lines.push(current);
      current = undefined;
    }
  };

  for (const rawLine of helpOutput.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line.length === 0) {
      flush();
      continue;
    }

    if (/^(?:-[A-Za-z0-9](?:,\s*|\s+))?--[A-Za-z0-9][A-Za-z0-9-]*(?=[=,\s]|$)/.test(line)) {
      flush();
      current = line;
      continue;
    }

    if (current != null) {
      current += ` ${line}`;
    }
  }
  flush();

  return lines;
}

function parseHelpFlagLine(line: string): ParsedHelpFlag[] {
  if (!line.includes("--")) {
    return [];
  }

  const optionMatch = /^(?:-[A-Za-z0-9](?:,\s*|\s+))?(--[A-Za-z0-9][A-Za-z0-9-]*)/.exec(line);
  if (optionMatch == null) {
    return [];
  }

  const [, cliName] = optionMatch;
  if (cliName == null) {
    return [];
  }
  const valueHint = findValueHint(line.slice(optionMatch[0].length));

  const values = parseEnumValues(valueHint, line);
  if (values.length > 0) {
    return [{ type: "enum", cliName, values, supported: true }];
  }

  return [
    {
      type: valueHint == null ? "boolean" : "string",
      cliName,
      supported: true,
    },
  ];
}

function findValueHint(suffix: string) {
  const withoutShortAlias = suffix.replace(/^,\s*-[A-Za-z0-9](?=\s|$)/, "");
  return /^\s*(?:=\s*)?(<[^>]+>|\[[^\]]+\]|(?:choice|dir|directory|file|int|integer|name|number|path|string|strings|value)\b|[A-Z][A-Z0-9_-]*\b)/.exec(
    withoutShortAlias,
  )?.[1];
}

function parseEnumValues(valueHint: string | undefined, line: string) {
  const fromHint = normalizeEnumValues(valueHint?.match(/[<[]([^>\]]*\|[^>\]]*)[>\]]/)?.[1]);
  if (
    fromHint.length > 0 &&
    !fromHint.every((value) => genericValueHints.has(value.toLowerCase()))
  ) {
    return fromHint;
  }

  for (const match of line.matchAll(/\(([^)]+)\)/g)) {
    const candidate = match[1];
    if (
      candidate == null ||
      (match.index != null && line[match.index - 1] === ".") ||
      (!candidate.includes(",") && !candidate.includes("|"))
    ) {
      continue;
    }
    const values = normalizeEnumValues(candidate);
    if (values.length > 0 && !values.every((value) => genericValueHints.has(value.toLowerCase()))) {
      return values;
    }
  }

  return [];
}

function normalizeEnumValues(value: string | undefined) {
  if (value == null) {
    return [];
  }

  const withoutDefault = value
    .replace(/^choices?:\s*/i, "")
    .replace(/(?:^|,|\|)\s*default(?:s to)?\s*:?.*$/i, "");
  const values = withoutDefault
    .split(withoutDefault.includes("|") ? "|" : ",")
    .map((candidate) => candidate.trim().replace(/^[`'"]|[`'"]$/g, ""))
    .filter(Boolean);

  return values.length > 1 && values.every((candidate) => /^[A-Za-z0-9_-]+$/.test(candidate))
    ? values
    : [];
}

function toFlagKey(cliName: string) {
  const words = cliName.replace(/^--/, "").split("-").filter(Boolean);
  return words
    .map((word, index) => (index === 0 ? word : `${word[0]?.toUpperCase() ?? ""}${word.slice(1)}`))
    .join("");
}

function isCliHelpForCommand(
  source: CliCommandManifest["sources"][number],
  commandId: string,
  commandCount: number,
): source is CliHelpSource {
  return (
    source.kind === "cli-help" &&
    (source.commandId === commandId || (source.commandId == null && commandCount === 1))
  );
}

export function resolvePackageManagerCommands(
  input: ManifestInput,
  version: string,
): PackageManagerCommandTemplates {
  const runner = input.runner === "auto" ? inferRunner(input.packageName) : input.runner;
  if (typeof runner === "object") {
    return Object.fromEntries(
      input.packageManagers.flatMap((packageManager) => {
        const template = runner[packageManager];
        return template == null
          ? []
          : [[packageManager, template.map((token) => token.replaceAll(version, "{version}"))]];
      }),
    );
  }

  if (runner === "create") {
    const initializer = getCreateInitializerName(input.packageName);
    return pickPackageManagers(input.packageManagers, {
      npm: ["npm", "init", `${initializer}@{version}`, "--"],
      pnpm: ["pnpm", "create", `${initializer}@{version}`],
      yarn: ["yarn", "create", `${initializer}@{version}`],
      bun: ["bun", "create", `${initializer}@{version}`],
      deno: ["deno", "x", "-A", `npm:${input.packageName}@{version}`],
    });
  }

  const subcommand = input.subcommand == null ? [] : [input.subcommand];
  return pickPackageManagers(input.packageManagers, {
    npm: ["npx", `${input.packageName}@{version}`, ...subcommand],
    pnpm: ["pnpm", "dlx", `${input.packageName}@{version}`, ...subcommand],
    yarn: ["yarn", "dlx", `${input.packageName}@{version}`, ...subcommand],
    bun: ["bunx", `${input.packageName}@{version}`, ...subcommand],
    deno: ["deno", "x", "-A", `npm:${input.packageName}@{version}`, ...subcommand],
  });
}

function createHelpCommand(input: ManifestInput, version: string) {
  const subcommand = input.subcommand == null ? [] : [input.subcommand];
  return ["npx", "--yes", `${input.packageName}@${version}`, ...subcommand, "--help"];
}

function inferRunner(packageName: string) {
  return getPackageNameWithoutScope(packageName).startsWith("create-") ? "create" : "dlx";
}

function getCreateInitializerName(packageName: string) {
  const scopedPackageMatch = /^(@[^/]+)\/(.+)$/.exec(packageName);
  if (scopedPackageMatch != null) {
    const [, scope, packageNameWithoutScope] = scopedPackageMatch;
    return `${scope}/${packageNameWithoutScope?.replace(/^create-/, "")}`;
  }

  return packageName.replace(/^create-/, "");
}

function getPackageNameWithoutScope(packageName: string) {
  return packageName.split("/").at(-1) ?? packageName;
}

function pickPackageManagers(
  packageManagers: readonly PackageManager[],
  templates: Required<PackageManagerCommandTemplates>,
) {
  return Object.fromEntries(
    packageManagers.map((packageManager) => [packageManager, templates[packageManager]]),
  );
}

function renderManifestWrapper(exportName: string) {
  return `${generatedFileHeader}
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import ${exportName}Data from "./manifest.generated.json";

export { ${exportName}Data };
export const ${exportName} = defineCliCommandManifest(${exportName}Data);
`;
}

function renderManifestRegistry(inputs: readonly ManifestInput[]): GeneratedFile {
  const imports = inputs
    .map(
      (input) =>
        `import { ${input.exportName}, ${input.exportName}Data } from "./${input.stackDir}/manifest";`,
    )
    .join("\n");
  const manifests = inputs.map((input) => `  ${input.exportName},`).join("\n");
  const manifestData = inputs.map((input) => `  ${input.exportName}Data,`).join("\n");

  return {
    path: path.resolve("src", "stacks", "manifest-registry.generated.ts"),
    content: `${generatedFileHeader}
import type { CliCommandManifest } from "../core/cli-command-manifest";
${imports}

export const cliCommandManifests = [
${manifests}
] satisfies readonly CliCommandManifest[];

export const cliCommandManifestData = [
${manifestData}
];

export function getCliCommandManifest(tool: string) {
  return cliCommandManifests.find((manifest) => manifest.tool === tool) ?? null;
}
`,
  };
}

function renderToolchainsRegistry(toolchains: readonly DiscoveredToolchain[]): GeneratedFile {
  const imports = toolchains
    .map(
      (toolchain) => `import { ${toolchain.exportName} } from "./${toolchain.stackDir}/adapter";`,
    )
    .join("\n");
  const registry = toolchains.map((toolchain) => `  ${toolchain.exportName},`).join("\n");
  const featureUnion = toolchains
    .map((toolchain) => `  | ${JSON.stringify(toolchain.adapter.feature)}`)
    .join("\n");

  return {
    path: path.resolve("src", "stacks", "toolchains.generated.ts"),
    content: `${generatedFileHeader}
import type { ToolchainAdapter } from "../core/toolchain-adapter";
${imports}

export const toolchains = [
${registry}
] satisfies readonly ToolchainAdapter[];

export type BuiltInFeature =
${featureUnion};

export const ALL_FEATURES = toolchains.map((toolchain) => toolchain.feature);

export function getSelectedToolchains(features: readonly string[]) {
  return toolchains.filter((toolchain) => features.includes(toolchain.feature));
}

export async function getAvailableToolchains(
  context: Parameters<NonNullable<(typeof toolchains)[number]["isAvailable"]>>[0],
) {
  const available = await Promise.all(
    toolchains.map(async (toolchain) => {
      const supportsPackageManager =
        toolchain.cli?.packageManagers?.includes(context.packageManager) ?? true;
      return {
        toolchain,
        isAvailable:
          supportsPackageManager && ((await toolchain.isAvailable?.(context)) ?? true),
      };
    }),
  );

  return available.filter(({ isAvailable }) => isAvailable).map(({ toolchain }) => toolchain);
}
`,
  };
}

function kebabCase(value: string) {
  return value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function isMainModule() {
  const entrypoint = process.argv[1];
  return entrypoint != null && import.meta.url === pathToFileURL(entrypoint).href;
}

function formatError(error: unknown) {
  if (error == null || typeof error !== "object") {
    return String(error);
  }

  const message = error instanceof Error ? error.message.split("\n")[0] : String(error);
  const stderr = "stderr" in error && typeof error.stderr === "string" ? error.stderr.trim() : "";
  const stdout = "stdout" in error && typeof error.stdout === "string" ? error.stdout.trim() : "";
  const output = [parseNpmViewError(stdout), stderr]
    .filter((value): value is string => value != null && value.length > 0)
    .join("\n");

  return output.length > 0 ? `${message}\n${output}` : message;
}

function parseNpmViewError(stdout: string) {
  if (stdout.length === 0) {
    return undefined;
  }

  try {
    const parsed = JSON.parse(stdout) as unknown;
    if (
      parsed != null &&
      typeof parsed === "object" &&
      "error" in parsed &&
      parsed.error != null &&
      typeof parsed.error === "object" &&
      "summary" in parsed.error &&
      typeof parsed.error.summary === "string"
    ) {
      return parsed.error.summary;
    }
  } catch {
    return stdout;
  }

  return stdout;
}
