// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import type { CliCommandManifest } from "../core/cli-command-manifest";
import {
  tanStackRouterCliManifest,
  tanStackRouterCliManifestData,
} from "./tanstack-router/manifest";
import { hotUpdaterCliManifest, hotUpdaterCliManifestData } from "./hot-updater/manifest";
import { prismaCliManifest, prismaCliManifestData } from "./prisma/manifest";
import { shadcnCliManifest, shadcnCliManifestData } from "./shadcn/manifest";
import { supabaseCliManifest, supabaseCliManifestData } from "./supabase/manifest";
import { playwrightCliManifest, playwrightCliManifestData } from "./playwright/manifest";
import { storybookCliManifest, storybookCliManifestData } from "./storybook/manifest";
import { mswCliManifest, mswCliManifestData } from "./msw/manifest";
import { oxfmtCliManifest, oxfmtCliManifestData } from "./oxfmt/manifest";
import { prettierCliManifest, prettierCliManifestData } from "./prettier/manifest";
import { oxlintCliManifest, oxlintCliManifestData } from "./oxlint/manifest";
import { eslintCliManifest, eslintCliManifestData } from "./eslint/manifest";
import { biomeCliManifest, biomeCliManifestData } from "./biome/manifest";
import { knipCliManifest, knipCliManifestData } from "./knip/manifest";
import { reactDoctorCliManifest, reactDoctorCliManifestData } from "./react-doctor/manifest";
import { changesetsCliManifest, changesetsCliManifestData } from "./changesets/manifest";
import { cspellCliManifest, cspellCliManifestData } from "./cspell/manifest";
import { publintCliManifest, publintCliManifestData } from "./publint/manifest";
import { attwCliManifest, attwCliManifestData } from "./are-the-types-wrong/manifest";
import { secretlintCliManifest, secretlintCliManifestData } from "./secretlint/manifest";
import { yarnSdksCliManifest, yarnSdksCliManifestData } from "./yarn-sdks/manifest";

export const cliCommandManifests = [
  tanStackRouterCliManifest,
  hotUpdaterCliManifest,
  prismaCliManifest,
  shadcnCliManifest,
  supabaseCliManifest,
  playwrightCliManifest,
  storybookCliManifest,
  mswCliManifest,
  oxfmtCliManifest,
  prettierCliManifest,
  oxlintCliManifest,
  eslintCliManifest,
  biomeCliManifest,
  knipCliManifest,
  reactDoctorCliManifest,
  changesetsCliManifest,
  cspellCliManifest,
  publintCliManifest,
  attwCliManifest,
  secretlintCliManifest,
  yarnSdksCliManifest,
] satisfies readonly CliCommandManifest[];

export const cliCommandManifestData = [
  tanStackRouterCliManifestData,
  hotUpdaterCliManifestData,
  prismaCliManifestData,
  shadcnCliManifestData,
  supabaseCliManifestData,
  playwrightCliManifestData,
  storybookCliManifestData,
  mswCliManifestData,
  oxfmtCliManifestData,
  prettierCliManifestData,
  oxlintCliManifestData,
  eslintCliManifestData,
  biomeCliManifestData,
  knipCliManifestData,
  reactDoctorCliManifestData,
  changesetsCliManifestData,
  cspellCliManifestData,
  publintCliManifestData,
  attwCliManifestData,
  secretlintCliManifestData,
  yarnSdksCliManifestData,
];

export function getCliCommandManifest(tool: string) {
  return cliCommandManifests.find((manifest) => manifest.tool === tool) ?? null;
}
