// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import type { CliCommandManifest } from "../core/cli-command-manifest";
import {
  tanStackRouterCliManifest,
  tanStackRouterCliManifestData,
} from "./tanstack-router/manifest";
import { hotUpdaterCliManifest, hotUpdaterCliManifestData } from "./hot-updater/manifest";
import { playwrightCliManifest, playwrightCliManifestData } from "./playwright/manifest";
import { storybookCliManifest, storybookCliManifestData } from "./storybook/manifest";
import { oxfmtCliManifest, oxfmtCliManifestData } from "./oxfmt/manifest";
import { prettierCliManifest, prettierCliManifestData } from "./prettier/manifest";
import { oxlintCliManifest, oxlintCliManifestData } from "./oxlint/manifest";
import { eslintCliManifest, eslintCliManifestData } from "./eslint/manifest";
import { biomeCliManifest, biomeCliManifestData } from "./biome/manifest";
import { knipCliManifest, knipCliManifestData } from "./knip/manifest";
import { reactDoctorCliManifest, reactDoctorCliManifestData } from "./react-doctor/manifest";
import { changesetsCliManifest, changesetsCliManifestData } from "./changesets/manifest";
import { yarnSdksCliManifest, yarnSdksCliManifestData } from "./yarn-sdks/manifest";

export const cliCommandManifests = [
  tanStackRouterCliManifest,
  hotUpdaterCliManifest,
  playwrightCliManifest,
  storybookCliManifest,
  oxfmtCliManifest,
  prettierCliManifest,
  oxlintCliManifest,
  eslintCliManifest,
  biomeCliManifest,
  knipCliManifest,
  reactDoctorCliManifest,
  changesetsCliManifest,
  yarnSdksCliManifest,
] satisfies readonly CliCommandManifest[];

export const cliCommandManifestData = [
  tanStackRouterCliManifestData,
  hotUpdaterCliManifestData,
  playwrightCliManifestData,
  storybookCliManifestData,
  oxfmtCliManifestData,
  prettierCliManifestData,
  oxlintCliManifestData,
  eslintCliManifestData,
  biomeCliManifestData,
  knipCliManifestData,
  reactDoctorCliManifestData,
  changesetsCliManifestData,
  yarnSdksCliManifestData,
];

export function getCliCommandManifest(tool: string) {
  return cliCommandManifests.find((manifest) => manifest.tool === tool) ?? null;
}
