// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import type { ToolchainDefinition } from "../core/toolchain-adapter";
import { hotUpdater } from "./hot-updater/adapter";
import { prisma } from "./prisma/adapter";
import { shadcn } from "./shadcn/adapter";
import { supabase } from "./supabase/adapter";
import { playwright } from "./playwright/adapter";
import { storybook } from "./storybook/adapter";
import { oxfmt } from "./oxfmt/adapter";
import { oxlint } from "./oxlint/adapter";
import { eslint } from "./eslint/adapter";
import { biome } from "./biome/adapter";
import { changesets } from "./changesets/adapter";
import { cspell } from "./cspell/adapter";
import { secretlint } from "./secretlint/adapter";
import { yarnSdks } from "./yarn-sdks/adapter";

export const toolchains = [
  hotUpdater,
  prisma,
  shadcn,
  supabase,
  playwright,
  storybook,
  oxfmt,
  oxlint,
  eslint,
  biome,
  changesets,
  cspell,
  secretlint,
  yarnSdks,
] satisfies readonly ToolchainDefinition[];

export type BuiltInToolId =
  | "hot-updater"
  | "prisma"
  | "shadcn"
  | "supabase"
  | "playwright"
  | "storybook"
  | "oxfmt"
  | "oxlint"
  | "eslint"
  | "biome"
  | "changesets"
  | "cspell"
  | "secretlint"
  | "yarn-sdks";

export const ALL_TOOL_IDS = toolchains.map((toolchain) => toolchain.id);

export function getSelectedToolchains(ids: readonly string[]) {
  const selectedIds = new Set(ids);
  return toolchains.filter((toolchain) => selectedIds.has(toolchain.id));
}
