// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import type { ToolchainAdapter } from "../core/toolchain-adapter";
import { tanStackRouter } from "./tanstack-router/adapter";
import { hotUpdater } from "./hot-updater/adapter";
import { playwright } from "./playwright/adapter";
import { storybook } from "./storybook/adapter";
import { msw } from "./msw/adapter";
import { oxfmt } from "./oxfmt/adapter";
import { prettier } from "./prettier/adapter";
import { oxlint } from "./oxlint/adapter";
import { eslint } from "./eslint/adapter";
import { biome } from "./biome/adapter";
import { knip } from "./knip/adapter";
import { reactDoctor } from "./react-doctor/adapter";
import { changesets } from "./changesets/adapter";
import { yarnSdks } from "./yarn-sdks/adapter";

export const toolchains = [
  tanStackRouter,
  hotUpdater,
  playwright,
  storybook,
  msw,
  oxfmt,
  prettier,
  oxlint,
  eslint,
  biome,
  knip,
  reactDoctor,
  changesets,
  yarnSdks,
] satisfies readonly ToolchainAdapter[];

export type BuiltInFeature =
  | "router"
  | "hotUpdater"
  | "playwright"
  | "storybook"
  | "msw"
  | "oxfmt"
  | "prettier"
  | "oxlint"
  | "eslint"
  | "biome"
  | "knip"
  | "reactDoctor"
  | "changesets"
  | "yarnSdks";

export const ALL_FEATURES = toolchains.map((toolchain) => toolchain.feature);

export function getSelectedToolchains(features: readonly string[]) {
  return toolchains.filter((toolchain) => features.includes(toolchain.feature));
}

export async function getAvailableToolchains(
  context: Parameters<NonNullable<(typeof toolchains)[number]["isAvailable"]>>[0],
) {
  const available = await Promise.all(
    toolchains.map(async (toolchain) => ({
      toolchain,
      isAvailable: (await toolchain.isAvailable?.(context)) ?? true,
    })),
  );

  return available.filter(({ isAvailable }) => isAvailable).map(({ toolchain }) => toolchain);
}
