// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import type { ToolchainAdapter } from "../core/toolchain-adapter";
import { tanStackRouter } from "./tanstack-router/adapter";
import { hotUpdater } from "./hot-updater/adapter";
import { prisma } from "./prisma/adapter";
import { shadcn } from "./shadcn/adapter";
import { supabase } from "./supabase/adapter";
import { playwright } from "./playwright/adapter";
import { storybook } from "./storybook/adapter";
import { msw } from "./msw/adapter";
import { oxfmt } from "./oxfmt/adapter";
import { prettier } from "./prettier/adapter";
import { oxlint } from "./oxlint/adapter";
import { eslint } from "./eslint/adapter";
import { biome } from "./biome/adapter";
import { knip } from "./knip/adapter";
import { reactDoctor } from "./react-doctor/adapter";
import { changesets } from "./changesets/adapter";
import { cspell } from "./cspell/adapter";
import { publint } from "./publint/adapter";
import { areTheTypesWrong } from "./are-the-types-wrong/adapter";
import { secretlint } from "./secretlint/adapter";
import { yarnSdks } from "./yarn-sdks/adapter";

export const toolchains = [
  tanStackRouter,
  hotUpdater,
  prisma,
  shadcn,
  supabase,
  playwright,
  storybook,
  msw,
  oxfmt,
  prettier,
  oxlint,
  eslint,
  biome,
  knip,
  reactDoctor,
  changesets,
  cspell,
  publint,
  areTheTypesWrong,
  secretlint,
  yarnSdks,
] satisfies readonly ToolchainAdapter[];

export type BuiltInFeature =
  | "router"
  | "hotUpdater"
  | "prisma"
  | "shadcn"
  | "supabase"
  | "playwright"
  | "storybook"
  | "msw"
  | "oxfmt"
  | "prettier"
  | "oxlint"
  | "eslint"
  | "biome"
  | "knip"
  | "reactDoctor"
  | "changesets"
  | "cspell"
  | "publint"
  | "areTheTypesWrong"
  | "secretlint"
  | "yarnSdks";

export const ALL_FEATURES = toolchains.map((toolchain) => toolchain.feature);

export function getSelectedToolchains(features: readonly string[]) {
  return features.flatMap((feature) =>
    toolchains.filter((toolchain) => toolchain.feature === feature),
  );
}
