// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import mswCliManifestData from "./manifest.generated.json";

export { mswCliManifestData };
export const mswCliManifest = defineCliCommandManifest(mswCliManifestData);
