// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";

export const reactDoctorCliManifest = defineCliCommandManifest({
  schemaVersion: "toolchains-init/cli-command-manifest/v1",
  tool: "react-doctor",
  package: "react-doctor",
  version: "0.7.1",
  commands: [
    {
      id: "check",
      packageManagers: {
        npm: ["npx", "react-doctor@{version}"],
        pnpm: ["pnpm", "dlx", "react-doctor@{version}"],
        yarn: ["yarn", "dlx", "react-doctor@{version}"],
      },
      interactive: true,
    },
  ],
  sources: [
    {
      kind: "npm",
      package: "react-doctor",
      version: "0.7.1",
      distTag: "latest",
      resolvedAt: "2026-07-04T09:08:37.294Z",
    },
    {
      kind: "cli-help",
      command: ["npx", "--yes", "react-doctor@0.7.1", "--help"],
    },
  ],
});
