// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import reactDoctorCliManifestData from "./manifest.generated.json";

export { reactDoctorCliManifestData };
export const reactDoctorCliManifest = defineCliCommandManifest(reactDoctorCliManifestData);
