// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import biomeCliManifestData from "./manifest.generated.json";

export { biomeCliManifestData };
export const biomeCliManifest = defineCliCommandManifest(biomeCliManifestData);
