// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import secretlintCliManifestData from "./manifest.generated.json";

export { secretlintCliManifestData };
export const secretlintCliManifest = defineCliCommandManifest(secretlintCliManifestData);
