// Generated by scripts/update-cli-manifests.ts. Do not edit directly.
import { defineCliCommandManifest } from "../../core/cli-command-manifest";
import hotUpdaterCliManifestData from "./manifest.generated.json";

export { hotUpdaterCliManifestData };
export const hotUpdaterCliManifest = defineCliCommandManifest(hotUpdaterCliManifestData);
